all:
	gcc -Wall -Werror -Wextra -D BUFFER_SIZE=1 get_next_line.c get_next_line_utils.c main.c

debug:
	gcc -Wall -Werror -Wextra -D BUFFER_SIZE=10 -g get_next_line.c get_next_line_utils.c main.c

fclean:
	rm -f *.o

